### ISSUE TITLE
Personalization Information

### ISSUE THREAD

**Issue by frogg** [OasysFoundation/Oasys-Organize#10]
What does personalization mean?
What's possible?

**Comment by frogg** [comment]
This is connected to #14. 
Do we need two issues for this?

**Comment by RobZuazua** [comment]
Yes, we need a clear definition of what personalization means for the Foundation. I think the AI agent is more specific, tackling maybe one part of personalization. @dlrenz correct me if I am wrong

**Comment by dlrenz** [comment]
answered this in #14 

i am finishing up right now the personalization info in the corresponding blog post folder. the doc is here

**Comment by dlrenz** [comment]
https://docs.google.com/document/d/18kf3w8nN7PPhoUOdI0q9zrOsK4iJYgAlYommhPCiEuY/

it also contains a grading of which teaching interventions are most effective, and ideas on how to tackle them using AI

**Comment by frogg** [comment]
This looks done. Can we close this issue?

**Comment by dlrenz** [comment]
yeah - more or less done ;)
