### ISSUE TITLE
Small AI Agent

### ISSUE THREAD

**Issue by frogg** [OasysFoundation/Oasys-Organize#14]
Chatbot?
Two types: Collaborative, plays with you
Tutoring agent: Answers questions

What are the most important teaching methods that AI can help with?

**Comment by RobZuazua** [comment]
any update on this? @dlrenz what is the objective of this issue?

**Comment by dlrenz** [comment]
this would have been a small chatbot integrated into the flagship experience.
as we are not actively working on that, and might not be absolutely necessary, i would close this issue for now
