### ISSUE TITLE
Thursday Meeting

### ISSUE THREAD

**Issue by frogg** [OasysFoundation/Oasys-Organize#16]
Discuss with Abtin on Thursday 
- Incorporation
- Foundation
- Funding

**Comment by RobZuazua** [comment]
can we make it 3pm or later?

**Comment by frogg** [comment]
Yep that should work.

**Comment by RobZuazua** [comment]
Let's prepare for the meeting here:

https://docs.google.com/document/d/177D-7D2_YWrXKKSL_8foOn0baDkziz1Ob35ZpVn7eXA/edit?usp=sharing
