### ISSUE TITLE
Graph + Skillprint UI

### ISSUE THREAD

**Issue by frogg** [OasysFoundation/Oasys-Organize#2]
Dashboards/interfaces for creators, teachers, users.

**Comment by frogg** [comment]
Most Important: Graph + Skillprint.
This has to be intuitive and mind-blowing because this is
1. our innovative approach
2. the entry point for new users
3. the anchor that we build our whole platform onto

**Comment by RobZuazua** [comment]
How are the wireframes different from the storyboard? The way i see it, I am creating 

1. Wireframes / Storyboard - a detailed screen by screen user flow
2. Sitemap - an easier way to view the user flow - maybe even on a single page

**Comment by RobZuazua** [comment]
[graph.pdf](https://github.com/OasysFoundation/Oasys-Organize/files/1925762/graph.pdf)
a high level overview of the graph structure. I'm not sure if the skillprint is at the core of the foundation. The skill print is futuristic and difficult if not impossible to implement now. To me, the skill print is a long term objective while the graph is the core. Let me know what you think

**Comment by frogg** [comment]
I know that @cocokiri also did some work on this yesterday and today. Not sure about the progress.

**Comment by frogg** [comment]
Deferring to next week to discuss the progress on that with @cocokiri.

**Comment by RobZuazua** [comment]
ok, Ill add this to Mondays meeting list

**Comment by frogg** [comment]
- we can have micro-educational content (twitter for simulations)
- discoverable and gradable
- host code on the graph
- mico-artistic expression

**Comment by RobZuazua** [comment]
@frogg @dlrenz @cocokiri which one of you all can make the full graph experience to where we can show it to VCs / advisors and get feedback on it? Right now, it is in static images and hard to explain / understand. If you want to pick up this task, add your name to the github issue and remove mine :) i feel like im not the best for this task

**Comment by frogg** [comment]
Still not sure how the skill print comes into our current mockups
