### ISSUE TITLE
Sketch out Architecture

### ISSUE THREAD

**Issue by frogg** [OasysFoundation/Oasys-Organize#21]
How does our platform work on a decentralized infrastructure?

- Encryption?
- Privacy?
- IPFS
- ERC 20
- BigChainDB
- Blockstack

This is mainly research, no implementation!

**Comment by frogg** [comment]
This is what we think so far:

# Blockstack
- user login
- user profile
- learning progress

# BigChainDB
- discussion board
- user messages

# IPFS
- actual games/simulations
- assets

# Ethereum
- Our OAS/CUR ERC-20 token
- Smart Contracts

**Comment by frogg** [comment]
This is how the data sharing could work using Blockstack.

<img width="500" alt="screen shot 2018-04-19 at 12 41 11" src="https://user-images.githubusercontent.com/5204169/38987118-01c09c54-43cf-11e8-9d68-d5eb051b05e6.png">

**Comment by dlrenz** [comment]
Why not just use Blockstack access control?

**Comment by frogg** [comment]
If that works, great! Haven't seen it in the documentation, yet.
Is it in the whitepaper?

**Comment by dlrenz** [comment]
It's one of the core points mentioned in the FAQ. Nothing about that in the API docs?

**Comment by frogg** [comment]
There might be a difference between access control between [User <—> App] and [User <—> User].

The [User <—> App] access control is definitely covered by Blockstack; I am not sure about the [User <—> User] scenario though.

**Comment by frogg** [comment]
Storing and reading content in Blockstack is also no problem:

## Reading a File from Blockstack:
```
blockstack.getFile("oasys.json").then((fileContents) =>
```

## Writing a File to Blockstack:
```
blockstack.putFile('oasys.json', "OASYS ROCKS")
```

**Comment by frogg** [comment]
Here's an overview of our currently planned architecture.

<img width="1054" alt="screen shot 2018-04-19 at 15 45 32" src="https://user-images.githubusercontent.com/5204169/38995213-bc2c066e-43e8-11e8-8b42-e11aaa26ba2f.png">

**Comment by RobZuazua** [comment]
@frogg, are you done with the decentralized architecture? When you are, lets schedule a call so you can explain it to me and we can iterate on the feature set / UI

**Comment by frogg** [comment]
@RobZuazua yep, it's as good as we can have it at this point I'd say.
We can talk after the token economy meeting.
