### ISSUE TITLE
Token Economy

### ISSUE THREAD

**Issue by frogg** [OasysFoundation/Oasys-Organize#22]
Robbie also worked out a high level token economy.

We need to be more clear on the market dynamics as well.

Also, Abtin wanted to send you feedback on this @RobZuazua.

**Comment by frogg** [comment]
https://medium.com/paratii/on-the-immaturity-of-tokenized-value-capture-mechanisms-1fde33f2bc8e

**Comment by RobZuazua** [comment]
I'm meeting with Abtin about this Monday if anyone wants to listen in. I am also working with some Econ friends to get a legitimate first draft out here by Friday!

**Comment by RobZuazua** [comment]
[token eco overview.pdf](https://github.com/OasysFoundation/Oasys-Organize/files/1959537/token.eco.overview.pdf)
