### ISSUE TITLE
Friday Pitch

### ISSUE THREAD

**Issue by frogg** [OasysFoundation/Oasys-Organize#25]
I'll prepare a pitch for tomorrow that includes this week's work:

- Vision
- Architecture, Tech
- Token Economy
- UI & User Flow
- Math Simulation and the idea behind that
- (Incorporation?)
- …am I missing something important?

**Comment by RobZuazua** [comment]
can you answer these questions with a convincing story? Maybe you can paint a picture of what this content would look like and why it is superior

- Why immersion / interactive content
- Target user / target buyer

**Comment by RobZuazua** [comment]
Instead of talking about the math simulation, what about talking about content creator tools. You can give an example of 2 or 3 including the math simulation

**Comment by RobZuazua** [comment]
Also, we need a roadmap !! I don't think we are ready to make an official road map yet but maybe you can put our main objectives down and an estimated time frame
