### ISSUE TITLE
Convertible note for investment

### ISSUE THREAD

**Issue by frogg** [OasysFoundation/Oasys-Organize#31]
We got some thoughts on convertibles which might be a good option to invest in a company without actually evaluating it right away.
Would that be compatible with a SAFT?

**Comment by RobZuazua** [comment]
https://hackernoon.com/the-ico-is-dead-long-live-the-ico-2-0-7bb269987513
https://thenextweb.com/hardfork/2018/04/21/ico-predictions-2018-big-changes-utility-tokens
https://hackernoon.com/security-tokens-are-doa-8ba1bb9f9368

The SEC and blockchain community seem to be ditching utility tokens. The SAFT will more than likely be ruled illegal by the SEC soon. The RATE is a legitimate, legal framework for raising money for ICOs. 

We should use the RATE framework for raising investment.
