### ISSUE TITLE
Oasys Platform Login Page

### ISSUE THREAD

**Issue by frogg** [OasysFoundation/Oasys-Organize#32]
Create a login page with Blockstack that allows logging into Oasys.

**Comment by frogg** [comment]
https://github.com/OasysFoundation/Oasys-Authentification

**Comment by RobZuazua** [comment]
@frogg, can you add to the readme and upload a picture or two so people have an idea of what you did. Including me :p

**Comment by frogg** [comment]
✅ added screenshots

https://github.com/OasysFoundation/Oasys-Authentication/blob/master/README.md
