### ISSUE TITLE
Friday Pitch

### ISSUE THREAD

**Issue by frogg** [OasysFoundation/Oasys-Organize#33]
We should have a clear pitch presentation for Friday, not just a weekly update on what we're doing.

**Comment by frogg** [comment]
Also depends on the output of #26

**Comment by RobZuazua** [comment]
Shouldn't we pitch #26? Why would we create two different pitch decks?

**Comment by frogg** [comment]
@RobZuazua yep, this is very similar to #26. 
We should definitely reuse the content/vision/ideas for the presentation pitch.

But this requires extra work: the _pitch deck_ is intended to be sent via email without a presenter (so there is much more text on it). The presentation should reduce the amount of text heavily and use more graphics and rhetoric elements.

**Comment by RobZuazua** [comment]
I do not agree with this. It seems confusing and counter productive to have two different decks. One deck, one message, consistent and concise.

**Comment by frogg** [comment]
@RobZuazua yep misunderstanding from my side. The pitch deck version that I've seen recently were actually containing Markus' notes which made it look more like a book than a presentation. This text is gonna be removed/reduced soon so we will have one consistent beautiful convincing pitch deck for email, meetings and pitches.

**Comment by frogg** [comment]
Pitch deck completed, no pitches today at hackmind.
