### ISSUE TITLE
Storyboard, User Journey

### ISSUE THREAD

**Issue by frogg** [OasysFoundation/Oasys-Organize#4]
User Flow

**Comment by frogg** [comment]
The storyboard/user journey really makes sense that you sent us @RobZuazua.

It's important to have this overview to see what features exist and how they work together. 

We'll iterate over it for sure later.

**Comment by RobZuazua** [comment]
Thanks! Ill post each part of the user flow here tonight after we do our iteration. Anyone who wants to be part of the discussion, let's meet at 5pm Berlin time on hangouts. 

https://hangouts.google.com/call/OVor14AUnaxlamwRl18qAAEE

**Comment by RobZuazua** [comment]
[user flow.pdf](https://github.com/OasysFoundation/Oasys-Organize/files/1925737/user.flow.pdf)

**Comment by frogg** [comment]
We should make sure that the UI is consistent with our latest architecture findings (I guess thats part of the iterative process 🙃).

We decided to go with Blockstack for now for authentication (login) and data storage, so there is no meta mask anymore.
Another question: How does the UI look like for the wallet and payment system?

**Comment by frogg** [comment]
Made this part of Milestone April 28 in order to iterate as mentioned above.

**Comment by RobZuazua** [comment]
@frogg what is the game plan for iterating on this? It has been hard to get quality feedback on this. would it help to make it digital? Can you help me come up with a plan on iterating on the user experience?

**Comment by frogg** [comment]
@RobZuazua I can create a digital version of it which is already one new iteration.
Having cleaner (digital) mockups makes it better understandable to external people I'd say.
From there on we can get more feedback, iterate and finally implement the real thing in the end.

**Comment by frogg** [comment]
This is an example of a rapid mockup (5 minutes).
Should I do that for all screens?

![oasys user interface 001](https://user-images.githubusercontent.com/5204169/39228417-676b51f0-485e-11e8-8b27-57779621d2e0.png)

**Comment by dlrenz** [comment]
I'd love that!
