### ISSUE TITLE
Create Visual for Concept Map

### ISSUE THREAD

**Issue by RobZuazua** [OasysFoundation/Oasys-Organize#42]
The visual should be self explanatory.

**Comment by RobZuazua** [comment]
@frogg , you may want to brainstorm with @cocokiri on this and maybe help him make this since markus will be doing a lot of pitch deck work

**Comment by dlrenz** [comment]
could you re-order this similar to how Markus did it in order to get a spatial dimension along which people learn? then it is much easier to show/understand progress.

**Comment by frogg** [comment]
the spacial dimension in this case is inside —> outside
when a node is learned it will merge into the center bubble
users can zoom into the center bubble again to see mastered nodes / previous games

**Comment by frogg** [comment]
updated according to feedback from comments & new color scheme:

<img width="1045" alt="image" src="https://user-images.githubusercontent.com/5204169/39759819-f6380d7c-52d3-11e8-83ff-683dba0abdc4.png">
