### ISSUE TITLE
Create Visual for Authoring Tools

### ISSUE THREAD

**Issue by RobZuazua** [OasysFoundation/Oasys-Organize#44]
The visual should be self explanatory

**Comment by RobZuazua** [comment]
@frogg , you may want to brainstorm with @cocokiri on this and maybe help him make this since markus will be doing a lot of pitch deck work.

Your visuals are always good :)

**Comment by frogg** [comment]
Yep, I'll take care of that. Is this visual supposed to be for MVP or Vision?

**Comment by frogg** [comment]
![image](https://user-images.githubusercontent.com/5204169/39665947-44ff274a-509c-11e8-9942-271b8436127f.png)

**Comment by frogg** [comment]
![image](https://user-images.githubusercontent.com/5204169/39930942-5034d75a-553c-11e8-9915-173425c89dd0.png)
