### ISSUE TITLE
Create Visual for Decentralized Architecture

### ISSUE THREAD

**Issue by RobZuazua** [OasysFoundation/Oasys-Organize#45]
- block stack
- ipfs
- mining through proof of learning 
- rewards through staking in Oasys bank
- Oasys bank
- integration with ethereum block chain
- WebRTC
- OAS connection to Ethereum

The visual should be self explanatory

**Comment by frogg** [comment]
What do you mean with visual in general? A mockup?

**Comment by RobZuazua** [comment]
@frogg, some way to help me understand how the tech would work. is the possible? For example, i want to print out this picture and take it to an ethereum meetup and be able to explain the tech stack with it and get feedback.

**Comment by frogg** [comment]
Sure, I'll work on that tomorrow! I'll post here once I have a first draft.

**Comment by dlrenz** [comment]
why single out webVR from all the web3d stuff?

**Comment by frogg** [comment]
@dlrenz yep you're right…probably better with Web3D in general so we don't exclude these use cases
![image](https://user-images.githubusercontent.com/5204169/39517998-d245e726-4e01-11e8-9794-ce0d6425fed4.png)

**Comment by RobZuazua** [comment]
looks good! :)
