### ISSUE TITLE
Token Economy Section Lightpaper

### ISSUE THREAD

**Issue by frogg** [OasysFoundation/Oasys-Organize#50]
Write about our incentivization structure of our platform and how the token economy works.

- proof of learning
- …

**Comment by RobZuazua** [comment]
[token Economy pdf.pdf](https://github.com/OasysFoundation/Oasys-Organize/files/1964935/token.Economy.pdf.pdf)

**Comment by dlrenz** [comment]
+1: the section is quite hard to understand, mainly because a motivation is lacking for most of the design choices. where possible, please provide an explanation.

**Comment by RobZuazua** [comment]
@frogg @dlrenz Thanks for the feedback, it was really helpful. I have updated the section with your suggestions. let me know what parts are still confusing!
