### ISSUE TITLE
Technology Section Lightpaper

### ISSUE THREAD

**Issue by frogg** [OasysFoundation/Oasys-Organize#51]
Describe how our decentralized architecture works.

**Comment by frogg** [comment]
Tech stack is now outlined in the lightpaper/

**Comment by RobZuazua** [comment]
nice, after the visual/visuals ill be able to better understand how everything ties together

**Comment by RobZuazua** [comment]
Do you have any friends / connections that you can discuss this tech stack with? I have a couple but I think it would be nice for me to have some visuals to explain it to people
